name: Build Pico-Game-Controller

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake gcc-arm-none-eabi build-essential python3

      - name: Get Pico SDK
        run: |
          git clone --recurse-submodules --depth 1 https://github.com/raspberrypi/pico-sdk
          echo "PICO_SDK_PATH=$PWD/pico-sdk" >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -DPICO_SDK_PATH=$PICO_SDK_PATH

      - name: Build firmware
        run: |
          cd build
          cmake --build . -- -j$(nproc)

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: pico-game-controller
          path: build/**/*.uf2
          if-no-files-found: error

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/**/*.uf2
          tag_name: latest
          name: Latest Build
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
