name: Build Pico-Game-Controller

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake gcc-arm-none-eabi build-essential python3 git

      - name: Set up Pico SDK
        run: |
          git clone --recurse-submodules --depth 1 https://github.com/raspberrypi/pico-sdk
          echo "PICO_SDK_PATH=$PWD/pico-sdk" >> $GITHUB_ENV

      - name: Configure project with CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -DPICO_SDK_PATH=$PICO_SDK_PATH

      - name: Build firmware
        run: |
          cd build
          cmake --build . --target all -- -j$(nproc)

      - name: Convert ELF to UF2
        run: |
          cd build
          cmake --build . --target Pico_Game_Controller.uf2

      - name: Upload UF2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: pico-game-controller
          path: build/Pico_Game_Controller.uf2
